name: Commitlint CI

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Print versions
        run: |          
          node --version
          npm --version
          npx commitlint --version
      - name: Install dependencies
        run: yarn

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from "${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}" --to "${{ github.event.pull_request.head.sha }}" --verbose
